#!/usr/bin/env bash

# Copyright (c) 2023 Eliah Kagan
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

set -e

readonly varpath='/workspaces/.codespaces/shared/environment-variables.json'
readonly confpath=~/.jupyter/jupyter_lab_config.py
readonly port='8888' # TODO: In the future, support a range of ports.
readonly domain_suffix='preview.app.github.dev'

if [ ! -e "$confpath" ]; then
    codespace="$(jq -r .CODESPACE_NAME -- "$varpath")"
    domain="$codespace-$port.$domain_suffix"
    mkdir -p -- "$(dirname -- "$confpath")"
    printf 'c = get_config()  # noqa\n' >"$confpath"
    printf "c.ServerApp.allow_origin = '%s'\n" "$domain" >>"$confpath"
fi
