name: algoviz

channels:
  - conda-forge

dependencies:
  - python=3.11
  - conda-build
  - more-itertools
  - sympy
  - typeguard

  # For notebooks
  - ipython>=8.1
  - jupyterlab>=3.1
  - nbdime

  # For Graphviz
  - graphviz
  - python-graphviz

  # For testing
  - parameterized
  - pytest
  - pytest-subtests

  # For static analysis
  - flake8
  - isort
  - mypy>=0.940
  - pylint
  - pyright
  - shellcheck
