name: palgoviz

channels:
  - conda-forge

dependencies:
  - python=3.11
  - ipykernel
  - more-itertools
  - numpy
  - sympy

  # For notebooks
  - ipython>=8.10
  - jupyterlab>=4
  - jupyter-collaboration
  - nbdime

  # For Graphviz
  - graphviz
  - python-graphviz

  # For testing (see also doctestfn)
  - parameterized
  - pytest
  - pytest-subtests

  # For static analysis
  - flake8
  - flake8-pyproject
  - isort

  # Some dependencies have no conda packages and so must be obtained from PyPI.
  - pip
  - pip:
    - doctestfn
