name: algoviz

channels:
  - conda-forge

dependencies:
  - python=3.11
  - conda-build
  - more-itertools
  - sympy

  # For notebooks
  - ipython>=8.1
  - jupyterlab>=3.1
  - nbdime

  # For Graphviz
  - graphviz
  - python-graphviz

  # For testing
  - parameterized
  - pytest
  - pytest-subtests

  # For static analysis
  - flake8
  - isort
  - shellcheck

  # Some dependencies have no conda packages and so must be obtained from PyPI.
  - pip
  - pip:
    - doctestfn # testing
    - Flake8-pyproject # static analysis
