name: algoviz

channels:
  - conda-forge

dependencies:
  - python=3.10
  - conda-build
  - greenlet
  - more-itertools
  - sympy

  # For Jupyter
  - ipython>=8.1
  - jupyterlab>=3.1
  - nbdime

  # For Graphviz
  - graphviz
  - python-graphviz

  # For testing
  - parameterized
  - pytest
  - pytest-subtests

  # For static analysis
  - flake8
  - isort
  - shellcheck
