#!/usr/bin/env bash

set -e
shopt -s globstar

. "$(dirname -- "$0")/shared.sh"

cd algoviz
module_filenames=(*)
cd - >/dev/null

modules="$(IFS='|'; printf '%s' "${module_filenames[*]%.py}")"

from_regexp='^([ ]{4}>>>[ ]+)?from[ ]+('"$modules"'([.][\w.]+)?)[ ]+import\b'
from_replacement='\1from algoviz.\2 import'

import_regexp='^([ ]{4}>>>[ ]+)?import[ ]+('"$modules"')[ ]*(\r?)$'
import_replacement='\1from algoviz import \2\3'

sed_script="
    s/$from_regexp/$from_replacement/
    s/$import_regexp/$import_replacement/
"

sed -bri "$sed_script" {algoviz,tests}/**/*.py
