#!/usr/bin/env bash

set -e
shopt -s failglob globstar

. "$(dirname -- "$0")/shared.sh" "$@"

cd algoviz
module_filenames=(*)
cd - >/dev/null

modules="$(IFS='|'; printf '%s' "${module_filenames[*]%.py}")"
front='^([ ]{4}(>>>|[.]{3}[ ]{4})[ ]+)?'  # NOTE: This has two capture groups.

from_regexp="$front"'from[ ]+('"$modules"'([.][\w.]+)?)[ ]+import\b'
from_replacement='\1from algoviz.\3 import'

import_regexp="$front"'import[ ]+('"$modules"')[ ]*(\r?)$'
import_replacement='\1from algoviz import \3\4'

sed_script="
    s/$from_regexp/$from_replacement/
    s/$import_regexp/$import_replacement/
"

sed -bri "$sed_script" algoviz/**/*.py tests/**/*.{py,txt}
