name: algoviz-basics-pytest

channels:
  - conda-forge

dependencies:
  - python=3.10
  - graphviz
  - ipython>=8.0.1
  - jupyterlab>=3.1
  - nbdime
  - pytest
  - python-graphviz
  - typeguard

  # dev
  - flake8
  - mypy
  - pylint
  - pyright
