name: algoviz-basics-linting

channels:
  - conda-forge

dependencies:
  - python=3.10
  - graphviz
  - ipython>=8.0.1
  - jupyterlab>=3.1
  - nbdime
  - python-graphviz

  # dev
  - flake8
  - pylint
