name: algoviz-basics-qa

channels:
  - conda-forge

dependencies:
  - python=3.10
  - more-itertools
  - typeguard

  # For Jupyter
  - ipython>=8.1
  - jupyterlab>=3.1
  - nbdime

  # For Graphviz
  - graphviz
  - python-graphviz

  # For testing
  - parameterized
  - pytest
  - pytest-subtests

  # For linting
  - flake8
  - mypy>=0.940
  - pylint
  - pyright
