name: algoviz-basics-pytest

channels:
  - conda-forge

dependencies:
  - python=3.10
  - graphviz
  - jupyterlab
  - pytest
  - python-graphviz

  # dev
  - mypy
  - pycodestyle
  - pylint
  - pyright
