name: algoviz-basics-linting

channels:
  - conda-forge

dependencies:
  - python=3.10

  # For Jupyter
  - ipython>=8.0.1
  - jupyterlab>=3.1
  - nbdime

  # For Graphviz
  - graphviz
  - python-graphviz

  # For testing
  - pytest

  # For linting
  - flake8
  - pylint
