#!/usr/bin/env bash

# Copyright (c) 2023 Eliah Kagan
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

set -e

readonly graphviz_version='7.1.0'

msg() {
    printf '%s: %s\n' "$0" "$1" >&2
}

nl() {
    printf '\n' >&2
}

msg 'Setting up poetry...'
pipx upgrade-all
pipx install poetry
msg '...poetry is set up.'

nl

msg 'Setting up conda and mamba...'
pushd /tmp
wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
chmod +x Mambaforge-Linux-x86_64.sh
./Mambaforge-Linux-x86_64.sh -b
rm Mambaforge-Linux-x86_64.sh
popd
~/mambaforge/bin/mamba init bash fish powershell zsh
~/mambaforge/bin/conda config --set auto_activate_base false
~/mambaforge/bin/mamba update --all --yes
msg '...conda and mamba are set up.'

nl

msg 'Building and installing Graphviz (for when using poetry)...'
pushd /tmp
wget "https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/$graphviz_version/graphviz-$graphviz_version.tar.xz"
tar xf "graphviz-$graphviz_version.tar.xz"
pushd "graphviz-$graphviz_version"
./configure
make
sudo make install # Assumes the user can run sudo without a password.
popd
rm -r "graphviz-$graphviz_version" "graphviz-$graphviz_version.tar.xz"
popd
msg '...built and installed Graphviz (for when using poetry).'

nl

msg 'Setting up project environment for poetry...'
poetry install
msg '...project environment for poetry is set up.'

nl

msg 'Setting up project environment for conda and mamba...'
~/mambaforge/bin/mamba env create
~/mambaforge/bin/mamba run -n palgoviz mamba develop .
msg '...project environment for conda and mamba is set up.'
