name: Check Markdown links

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 0,12 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
