name: "pytest (all tests, conda)"

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Provision with micromamba
        uses: mamba-org/provision-with-micromamba@v15

      - name: Make editable install
        run: pip install -e .

      - name: Run all tests
        run: pytest --doctest-modules
        timeout-minutes: 2
