name: 'pytest (all tests, poetry)'

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - poetry: ~/.local/bin/poetry

          - os: windows-latest
            poetry: |-
              "$APPDATA/Python/Scripts/poetry"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # TODO: Print the install script commit hash and Poetry version.
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/EliahKagan/install.python-poetry.org/ci-repro/palgoviz/install-poetry.py |
              python3 -

      - name: Install project and test runner
        run: ${{ matrix.poetry }} install --only=main,test

      - name: Run all tests
        run: ${{ matrix.poetry }} run pytest --doctest-modules
        timeout-minutes: 2
