name: Tests (current, conda)

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        runner: [pytest, unittest, doctest]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - runner: pytest
            description: Run all tests (pytest)
            command: pytest --doctest-modules

          - runner: unittest
            description: Run unittest tests
            command: python -m unittest

          - runner: doctest
            description: Run doctests
            command: python -m doctest palgoviz/*.py tests/*.py tests/*.txt

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Provision with micromamba
        uses: mamba-org/provision-with-micromamba@v15

      - name: Make editable install
        run: pip install -e .

      - name: ${{ matrix.description }}
        run: ${{ matrix.command }}
        timeout-minutes: 2
