name: Tests (current, poetry)

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        test-step-id: [pytest, unittest, doctest]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - test-step-id: pytest
            test-step-name: Run all tests (pytest)
            test-step-command: pytest --doctest-modules

          - test-step-id: unittest
            test-step-name: Run unittest tests
            test-step-command: python -m unittest

          - test-step-id: doctest
            test-step-name: Run doctests
            test-step-command: |
              python -m doctest palgoviz/*.py tests/*.py tests/*.txt

          - poetry: ~/.local/bin/poetry

          - os: windows-latest
            poetry: |-
              "$APPDATA/Python/Scripts/poetry"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # TODO: Print the install script commit hash and Poetry version.
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/EliahKagan/install.python-poetry.org/ci-repro/palgoviz/install-poetry.py |
              python3 -

      - name: Install project and test runner
        run: ${{ matrix.poetry }} install --only=main,test

      - name: ${{ matrix.test-step-name }}
        id: ${{ matrix.test-step-id }}
        run: ${{ matrix.poetry }} run ${{ matrix.test-step-command }}
        timeout-minutes: 2
