name: Tests (current, poetry)

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        runner: [pytest, unittest, doctest]
        os: [ubuntu, macos, windows]
        include:
          - runner: pytest
            description: Run all tests (pytest)
            command: pytest --doctest-modules

          # Including this here as well as in tests-compatible-poetry.yml runs
          # the unittest runner both with frozen poetry.lock package versions
          # (this workflow) and non-frozen package versions (that workflow).
          # This differs from conda, where we're not freezing package versions.
          # so the unittest runner is listed in tests-compatible-conda.yml but
          # not also tests-current-conda.yml. So having it in both of those
          # would always test exactly the same configuration and behavior.
          - runner: unittest
            description: Run unittest tests
            command: python -m unittest

          - runner: doctest
            description: Run doctests
            command: python -m doctest palgoviz/*.py tests/*.py tests/*.txt

          - poetry: ~/.local/bin/poetry

          - os: windows
            poetry: |-
              "$APPDATA/Python/Scripts/poetry"

    runs-on: ${{ matrix.os }}-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # TODO: Print the install script commit hash and Poetry version.
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/EliahKagan/install.python-poetry.org/ci-repro/palgoviz/install-poetry.py |
              python3 -

      - name: Install project and test runner
        run: ${{ matrix.poetry }} install --only=main,test

      - name: ${{ matrix.description }}
        run: ${{ matrix.poetry }} run ${{ matrix.command }}
        timeout-minutes: 2
